id: I704BE77A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T08:53:35+00:00'
last_modified: '2022-06-08T04:45:49.356489+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29468
  title: བཀའ་འགྱུར ༼ཨུརྒ༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    E898:
      image_group_id: I5295
      title: ''
      total_pages: 626
      order: 1
      base_file: E898.txt
    37AB:
      image_group_id: I5296
      title: ''
      total_pages: 638
      order: 2
      base_file: 37AB.txt
    95C6:
      image_group_id: I5297
      title: ''
      total_pages: 590
      order: 3
      base_file: 95C6.txt
    E5F3:
      image_group_id: I5298
      title: ''
      total_pages: 608
      order: 4
      base_file: E5F3.txt
    28CD:
      image_group_id: I5299
      title: ''
      total_pages: 588
      order: 5
      base_file: 28CD.txt
    '8803':
      image_group_id: I5300
      title: ''
      total_pages: 578
      order: 6
      base_file: 8803.txt
    '0152':
      image_group_id: I5301
      title: ''
      total_pages: 578
      order: 7
      base_file: 0152.txt
    8B84:
      image_group_id: I5302
      title: ''
      total_pages: 542
      order: 8
      base_file: 8B84.txt
    FF41:
      image_group_id: I5303
      title: ''
      total_pages: 660
      order: 9
      base_file: FF41.txt
    '3130':
      image_group_id: I5304
      title: ''
      total_pages: 624
      order: 10
      base_file: 3130.txt
    '0735':
      image_group_id: I5305
      title: ''
      total_pages: 670
      order: 11
      base_file: 0735.txt
    0E3E:
      image_group_id: I5306
      title: ''
      total_pages: 606
      order: 12
      base_file: 0E3E.txt
    '0077':
      image_group_id: I5307
      title: ''
      total_pages: 630
      order: 13
      base_file: 0077.txt
    80FF:
      image_group_id: I5308
      title: ''
      total_pages: 792
      order: 14
      base_file: 80FF.txt
    C622:
      image_group_id: I5346
      title: ''
      total_pages: 690
      order: 52
      base_file: C622.txt
    15D2:
      image_group_id: I5310
      title: ''
      total_pages: 792
      order: 16
      base_file: 15D2.txt
    '0444':
      image_group_id: I5311
      title: ''
      total_pages: 766
      order: 17
      base_file: 0444.txt
    40DB:
      image_group_id: I5312
      title: ''
      total_pages: 794
      order: 18
      base_file: 40DB.txt
    8A04:
      image_group_id: I5313
      title: ''
      total_pages: 770
      order: 19
      base_file: 8A04.txt
    499E:
      image_group_id: I5314
      title: ''
      total_pages: 800
      order: 20
      base_file: 499E.txt
    940E:
      image_group_id: I5315
      title: ''
      total_pages: 802
      order: 21
      base_file: 940E.txt
    CAA3:
      image_group_id: I5316
      title: ''
      total_pages: 772
      order: 22
      base_file: CAA3.txt
    2AC7:
      image_group_id: I5317
      title: ''
      total_pages: 780
      order: 23
      base_file: 2AC7.txt
    22E3:
      image_group_id: I5318
      title: ''
      total_pages: 826
      order: 24
      base_file: 22E3.txt
    C14B:
      image_group_id: I5319
      title: ''
      total_pages: 794
      order: 25
      base_file: C14B.txt
    1BC0:
      image_group_id: I5320
      title: ''
      total_pages: 768
      order: 26
      base_file: 1BC0.txt
    '8370':
      image_group_id: I5321
      title: ''
      total_pages: 790
      order: 27
      base_file: 8370.txt
    EAF0:
      image_group_id: I5322
      title: ''
      total_pages: 764
      order: 28
      base_file: EAF0.txt
    '2444':
      image_group_id: I5323
      title: ''
      total_pages: 604
      order: 29
      base_file: 2444.txt
    55E4:
      image_group_id: I5324
      title: ''
      total_pages: 612
      order: 30
      base_file: 55E4.txt
    8FEF:
      image_group_id: I5325
      title: ''
      total_pages: 416
      order: 31
      base_file: 8FEF.txt
    '4336':
      image_group_id: I5326
      title: ''
      total_pages: 796
      order: 32
      base_file: 4336.txt
    '2000':
      image_group_id: I5327
      title: ''
      total_pages: 578
      order: 33
      base_file: 2000.txt
    FD64:
      image_group_id: I5328
      title: ''
      total_pages: 572
      order: 34
      base_file: FD64.txt
    D5A0:
      image_group_id: I5329
      title: ''
      total_pages: 790
      order: 35
      base_file: D5A0.txt
    612D:
      image_group_id: I5330
      title: ''
      total_pages: 796
      order: 36
      base_file: 612D.txt
    A99A:
      image_group_id: I5369
      title: ''
      total_pages: 600
      order: 75
      base_file: A99A.txt
    1A56:
      image_group_id: I5332
      title: ''
      total_pages: 734
      order: 38
      base_file: 1A56.txt
    F2C4:
      image_group_id: I5333
      title: ''
      total_pages: 544
      order: 39
      base_file: F2C4.txt
    89DF:
      image_group_id: I5334
      title: ''
      total_pages: 594
      order: 40
      base_file: 89DF.txt
    2CBB:
      image_group_id: I5335
      title: ''
      total_pages: 652
      order: 41
      base_file: 2CBB.txt
    5A5A:
      image_group_id: I5336
      title: ''
      total_pages: 584
      order: 42
      base_file: 5A5A.txt
    C3B7:
      image_group_id: I5337
      title: ''
      total_pages: 624
      order: 43
      base_file: C3B7.txt
    E0FC:
      image_group_id: I5338
      title: ''
      total_pages: 602
      order: 44
      base_file: E0FC.txt
    BD2A:
      image_group_id: I5339
      title: ''
      total_pages: 684
      order: 45
      base_file: BD2A.txt
    '8635':
      image_group_id: I5340
      title: ''
      total_pages: 560
      order: 46
      base_file: 8635.txt
    EA15:
      image_group_id: I5341
      title: ''
      total_pages: 614
      order: 47
      base_file: EA15.txt
    '2787':
      image_group_id: I5342
      title: ''
      total_pages: 580
      order: 48
      base_file: 2787.txt
    8F78:
      image_group_id: I5343
      title: ''
      total_pages: 588
      order: 49
      base_file: 8F78.txt
    D08A:
      image_group_id: I5344
      title: ''
      total_pages: 596
      order: 50
      base_file: D08A.txt
    4AD4:
      image_group_id: I5345
      title: ''
      total_pages: 600
      order: 51
      base_file: 4AD4.txt
    BB30:
      image_group_id: I5347
      title: ''
      total_pages: 682
      order: 53
      base_file: BB30.txt
    42A5:
      image_group_id: I5348
      title: ''
      total_pages: 588
      order: 54
      base_file: 42A5.txt
    315A:
      image_group_id: I5349
      title: ''
      total_pages: 636
      order: 55
      base_file: 315A.txt
    8C33:
      image_group_id: I5350
      title: ''
      total_pages: 604
      order: 56
      base_file: 8C33.txt
    D5C5:
      image_group_id: I5351
      title: ''
      total_pages: 692
      order: 57
      base_file: D5C5.txt
    78BB:
      image_group_id: I5352
      title: ''
      total_pages: 642
      order: 58
      base_file: 78BB.txt
    3F24:
      image_group_id: I5353
      title: ''
      total_pages: 632
      order: 59
      base_file: 3F24.txt
    FEAD:
      image_group_id: I5354
      title: ''
      total_pages: 596
      order: 60
      base_file: FEAD.txt
    1A09:
      image_group_id: I5355
      title: ''
      total_pages: 622
      order: 61
      base_file: 1A09.txt
    8E4C:
      image_group_id: I5356
      title: ''
      total_pages: 618
      order: 62
      base_file: 8E4C.txt
    9B4B:
      image_group_id: I5357
      title: ''
      total_pages: 598
      order: 63
      base_file: 9B4B.txt
    F260:
      image_group_id: I5358
      title: ''
      total_pages: 604
      order: 64
      base_file: F260.txt
    '6633':
      image_group_id: I5359
      title: ''
      total_pages: 616
      order: 65
      base_file: 6633.txt
    99FC:
      image_group_id: I5360
      title: ''
      total_pages: 630
      order: 66
      base_file: 99FC.txt
    330A:
      image_group_id: I5361
      title: ''
      total_pages: 642
      order: 67
      base_file: 330A.txt
    1C6B:
      image_group_id: I5362
      title: ''
      total_pages: 640
      order: 68
      base_file: 1C6B.txt
    03CC:
      image_group_id: I5363
      title: ''
      total_pages: 618
      order: 69
      base_file: 03CC.txt
    55C4:
      image_group_id: I5364
      title: ''
      total_pages: 628
      order: 70
      base_file: 55C4.txt
    E265:
      image_group_id: I5365
      title: ''
      total_pages: 614
      order: 71
      base_file: E265.txt
    EB14:
      image_group_id: I5366
      title: ''
      total_pages: 676
      order: 72
      base_file: EB14.txt
    '6688':
      image_group_id: I5367
      title: ''
      total_pages: 622
      order: 73
      base_file: 6688.txt
    DCEB:
      image_group_id: I5368
      title: ''
      total_pages: 604
      order: 74
      base_file: DCEB.txt
    FCD4:
      image_group_id: I5370
      title: ''
      total_pages: 568
      order: 76
      base_file: FCD4.txt
    '8245':
      image_group_id: I5371
      title: ''
      total_pages: 310
      order: 77
      base_file: 8245.txt
    '3810':
      image_group_id: I5372
      title: ''
      total_pages: 738
      order: 78
      base_file: 3810.txt
    253E:
      image_group_id: I5373
      title: ''
      total_pages: 626
      order: 79
      base_file: 253E.txt
    8DD3:
      image_group_id: I5374
      title: ''
      total_pages: 588
      order: 80
      base_file: 8DD3.txt
    5D89:
      image_group_id: I5375
      title: ''
      total_pages: 690
      order: 81
      base_file: 5D89.txt
    BB27:
      image_group_id: I5376
      title: ''
      total_pages: 576
      order: 82
      base_file: BB27.txt
    00FB:
      image_group_id: I5377
      title: ''
      total_pages: 712
      order: 83
      base_file: 00FB.txt
    4DB6:
      image_group_id: I5378
      title: ''
      total_pages: 610
      order: 84
      base_file: 4DB6.txt
    0B5C:
      image_group_id: I5379
      title: ''
      total_pages: 552
      order: 85
      base_file: 0B5C.txt
    59A6:
      image_group_id: I5380
      title: ''
      total_pages: 548
      order: 86
      base_file: 59A6.txt
    '8325':
      image_group_id: I5381
      title: ''
      total_pages: 650
      order: 87
      base_file: 8325.txt
    5D66:
      image_group_id: I5382
      title: ''
      total_pages: 620
      order: 88
      base_file: 5D66.txt
    B2F4:
      image_group_id: I5383
      title: ''
      total_pages: 708
      order: 89
      base_file: B2F4.txt
    4BF6:
      image_group_id: I5384
      title: ''
      total_pages: 588
      order: 90
      base_file: 4BF6.txt
    1C13:
      image_group_id: I5385
      title: ''
      total_pages: 576
      order: 91
      base_file: 1C13.txt
    16E4:
      image_group_id: I5386
      title: ''
      total_pages: 576
      order: 92
      base_file: 16E4.txt
    AD43:
      image_group_id: I5387
      title: ''
      total_pages: 636
      order: 93
      base_file: AD43.txt
    69F4:
      image_group_id: I5388
      title: ''
      total_pages: 624
      order: 94
      base_file: 69F4.txt
    CAA6:
      image_group_id: I5389
      title: ''
      total_pages: 558
      order: 95
      base_file: CAA6.txt
    4C8B:
      image_group_id: I5390
      title: ''
      total_pages: 592
      order: 96
      base_file: 4C8B.txt
    7BE7:
      image_group_id: I5391
      title: ''
      total_pages: 530
      order: 97
      base_file: 7BE7.txt
    3DAA:
      image_group_id: I5392
      title: ''
      total_pages: 720
      order: 98
      base_file: 3DAA.txt
    B21D:
      image_group_id: I5393
      title: ''
      total_pages: 626
      order: 99
      base_file: B21D.txt
    44F5:
      image_group_id: I5394
      title: ''
      total_pages: 580
      order: 100
      base_file: 44F5.txt
    22D1:
      image_group_id: I5395
      title: ''
      total_pages: 570
      order: 101
      base_file: 22D1.txt
    2C9A:
      image_group_id: I5396
      title: ''
      total_pages: 560
      order: 102
      base_file: 2C9A.txt
    '3438':
      image_group_id: I5397
      title: ''
      total_pages: 714
      order: 103
      base_file: 3438.txt
    '8334':
      image_group_id: I5398
      title: ''
      total_pages: 236
      order: 104
      base_file: 8334.txt
    '0430':
      image_group_id: I5399
      title: ''
      total_pages: 152
      order: 105
      base_file: 0430.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
