id: P005538
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W29468
  title: བཀའ་འགྱུར ༼ཨུརྒ༽
  author: ''
  volumes:
    65a2f96b90794659b233c70b8e3766d2:
      image_group_id: I5295
      title: ''
      volume_number: 1
      total_pages: 626
      base_file: v004.txt
    0181ad3dc10b42b299a5a9e637e2829f:
      image_group_id: I5296
      title: ''
      volume_number: 2
      total_pages: 638
      base_file: v002.txt
    c2d5dfa3e51242a69c574425e6880a23:
      image_group_id: I5297
      title: ''
      volume_number: 3
      total_pages: 590
      base_file: v003.txt
    4d929ae2cbac4bdf89557087d28bcd8a:
      image_group_id: I5298
      title: ''
      volume_number: 4
      total_pages: 608
    ea797c64f133472e954ba3c9d5c5b150:
      image_group_id: I5299
      title: ''
      volume_number: 5
      total_pages: 588
      base_file: v005.txt
    cc9ab1b621b54b36ae43d7cd0022e860:
      image_group_id: I5300
      title: ''
      volume_number: 6
      total_pages: 578
      base_file: v006.txt
    61627029620447ce93ed3429742a9d4d:
      image_group_id: I5301
      title: ''
      volume_number: 7
      total_pages: 578
      base_file: v007.txt
    6376f3d770f04289a77a0c7cbeb54a46:
      image_group_id: I5302
      title: ''
      volume_number: 8
      total_pages: 542
      base_file: v008.txt
    750e7dc6e5b34f38bb30eaaf59043b96:
      image_group_id: I5303
      title: ''
      volume_number: 9
      total_pages: 660
      base_file: v009.txt
    75237d1e189b42489df9ec4c49b90e05:
      image_group_id: I5304
      title: ''
      volume_number: 10
      total_pages: 624
      base_file: v010.txt
    7533804c7dbc422d8eb486e146517538:
      image_group_id: I5305
      title: ''
      volume_number: 11
      total_pages: 670
      base_file: v011.txt
    c96069cb07d44d429ebb0f5d29f1fa19:
      image_group_id: I5306
      title: ''
      volume_number: 12
      total_pages: 606
      base_file: v012.txt
    ad729b93b68140198008e967b2dfcbd5:
      image_group_id: I5307
      title: ''
      volume_number: 13
      total_pages: 630
      base_file: v013.txt
    79256a644ffc4f6cb675829992c3c8a7:
      image_group_id: I5308
      title: ''
      volume_number: 14
      total_pages: 792
      base_file: v014.txt
    a29d009f28334a948404ae1b8caf5bb8:
      image_group_id: I5309
      title: ''
      volume_number: 15
      total_pages: 808
      base_file: v015.txt
    9255b4f59b9d4ad0a78172a911db63ff:
      image_group_id: I5310
      title: ''
      volume_number: 16
      total_pages: 792
      base_file: v016.txt
    6df7a5818c09469dbdbcfb13e9d32ecc:
      image_group_id: I5311
      title: ''
      volume_number: 17
      total_pages: 766
      base_file: v017.txt
    daf5784bc79c4d41a938650f33f1068e:
      image_group_id: I5312
      title: ''
      volume_number: 18
      total_pages: 794
      base_file: v018.txt
    4f5db6bb3db140f792ae257ebacdffdf:
      image_group_id: I5313
      title: ''
      volume_number: 19
      total_pages: 770
      base_file: v019.txt
    830569c138d94465af8dc5cccfa702ed:
      image_group_id: I5314
      title: ''
      volume_number: 20
      total_pages: 800
      base_file: v020.txt
    795b8d360de74da381680251fdc12bb2:
      image_group_id: I5315
      title: ''
      volume_number: 21
      total_pages: 802
      base_file: v021.txt
    00fa213edeb04f7dbcc8ce7de733eb58:
      image_group_id: I5316
      title: ''
      volume_number: 22
      total_pages: 772
      base_file: v022.txt
    f693850d907e4e4391bbfb707f7a4adc:
      image_group_id: I5317
      title: ''
      volume_number: 23
      total_pages: 780
      base_file: v023.txt
    3a0625fea36741ef959bec0de255397a:
      image_group_id: I5318
      title: ''
      volume_number: 24
      total_pages: 826
      base_file: v024.txt
    a604e6a036934b89bfa3e4f806602dee:
      image_group_id: I5319
      title: ''
      volume_number: 25
      total_pages: 794
      base_file: v025.txt
    e19e918f062b484f9f12d10d2952833b:
      image_group_id: I5320
      title: ''
      volume_number: 26
      total_pages: 768
      base_file: v026.txt
    5dcffedab85447bab90f51cdc276f931:
      image_group_id: I5321
      title: ''
      volume_number: 27
      total_pages: 790
      base_file: v027.txt
    6f36986466b246d0b8428a46748a69c0:
      image_group_id: I5322
      title: ''
      volume_number: 28
      total_pages: 764
      base_file: v028.txt
    57eb48ec66cf4d4abe513b0ec5754afe:
      image_group_id: I5323
      title: ''
      volume_number: 29
      total_pages: 604
      base_file: v029.txt
    e48b7bb04c9747be8346a66bd8f9ea17:
      image_group_id: I5324
      title: ''
      volume_number: 30
      total_pages: 612
      base_file: v030.txt
    fd83c74aa0ac4b999a342a3564ff699e:
      image_group_id: I5325
      title: ''
      volume_number: 31
      total_pages: 416
      base_file: v031.txt
    1c8a263c5035491580df3b07340bb694:
      image_group_id: I5326
      title: ''
      volume_number: 32
      total_pages: 796
      base_file: v032.txt
    0ce84cfd8c7a48648b73b681a9292be7:
      image_group_id: I5327
      title: ''
      volume_number: 33
      total_pages: 578
      base_file: v033.txt
    f7d52d7db8d44e139055229fbbbce1ca:
      image_group_id: I5328
      title: ''
      volume_number: 34
      total_pages: 572
      base_file: v034.txt
    7dbfb6b78cb247a6aefcb0541582d04a:
      image_group_id: I5329
      title: ''
      volume_number: 35
      total_pages: 790
      base_file: v035.txt
    4c9534fe860845ab99ff3a31a146f9db:
      image_group_id: I5330
      title: ''
      volume_number: 36
      total_pages: 796
      base_file: v036.txt
    a9b4db033d9e4c09bfaf1e28a80e8203:
      image_group_id: I5331
      title: ''
      volume_number: 37
      total_pages: 794
      base_file: v037.txt
    a51709fd66524120991b54860900dc47:
      image_group_id: I5332
      title: ''
      volume_number: 38
      total_pages: 734
      base_file: v038.txt
    6a34a9738804414280d893dab9d84bd2:
      image_group_id: I5333
      title: ''
      volume_number: 39
      total_pages: 544
      base_file: v039.txt
    027ff75c256d406e9f468eb83a769d7c:
      image_group_id: I5334
      title: ''
      volume_number: 40
      total_pages: 594
      base_file: v040.txt
    ed59165ec1d14091b98420c575190a52:
      image_group_id: I5335
      title: ''
      volume_number: 41
      total_pages: 652
      base_file: v041.txt
    120058e63e6a464fb947afc6aef7bdc2:
      image_group_id: I5336
      title: ''
      volume_number: 42
      total_pages: 584
      base_file: v042.txt
    caca01c9fcea4c6db4014a352e3dde4d:
      image_group_id: I5337
      title: ''
      volume_number: 43
      total_pages: 624
      base_file: v043.txt
    8042ce510a7948069a4dd8a9c89b0680:
      image_group_id: I5338
      title: ''
      volume_number: 44
      total_pages: 602
      base_file: v044.txt
    176891b5ba8b4ca085bd2d905f14e7bb:
      image_group_id: I5339
      title: ''
      volume_number: 45
      total_pages: 684
      base_file: v045.txt
    50f7f2e8dc2a42c282938028e74ef9e6:
      image_group_id: I5340
      title: ''
      volume_number: 46
      total_pages: 560
      base_file: v046.txt
    fb872f2c8d5942ed8cfffa49a40dbf22:
      image_group_id: I5341
      title: ''
      volume_number: 47
      total_pages: 614
      base_file: v047.txt
    35835fc62a074b63b5132f38f2c438af:
      image_group_id: I5342
      title: ''
      volume_number: 48
      total_pages: 580
      base_file: v048.txt
    78aa4d69a66142cbbffa5991c9c98c1e:
      image_group_id: I5343
      title: ''
      volume_number: 49
      total_pages: 588
      base_file: v049.txt
    b5a2a50f2a2b4543b3b318c9fcfeff67:
      image_group_id: I5344
      title: ''
      volume_number: 50
      total_pages: 596
      base_file: v050.txt
    210d42435cc34d09bfb4930c452458e2:
      image_group_id: I5345
      title: ''
      volume_number: 51
      total_pages: 600
      base_file: v051.txt
    b99ae5c917e742199fcf4d7765072360:
      image_group_id: I5346
      title: ''
      volume_number: 52
      total_pages: 690
      base_file: v052.txt
    18ad405e5c7b4a2d8f960f703fe976ea:
      image_group_id: I5347
      title: ''
      volume_number: 53
      total_pages: 682
      base_file: v053.txt
    4878e6a8cb72490fa1552b1a45c36c01:
      image_group_id: I5348
      title: ''
      volume_number: 54
      total_pages: 588
      base_file: v054.txt
    f9999468d8834fdd8dba23775aa55374:
      image_group_id: I5349
      title: ''
      volume_number: 55
      total_pages: 636
      base_file: v055.txt
    257d68e44a594471be5a5e50093db9ec:
      image_group_id: I5350
      title: ''
      volume_number: 56
      total_pages: 604
      base_file: v056.txt
    e7bc27a03090430b81654b2389b48f08:
      image_group_id: I5351
      title: ''
      volume_number: 57
      total_pages: 692
      base_file: v057.txt
    4f4a8a2d49a142aeb0904070b6c1b29f:
      image_group_id: I5352
      title: ''
      volume_number: 58
      total_pages: 642
      base_file: v058.txt
    16bc10e35f0b47338d7b6ad6da36b303:
      image_group_id: I5353
      title: ''
      volume_number: 59
      total_pages: 632
      base_file: v059.txt
    0b1e4aee89cb47c8ad65f290a1f24349:
      image_group_id: I5354
      title: ''
      volume_number: 60
      total_pages: 596
      base_file: v060.txt
    2797626797744cac9eced9ff6f03cd93:
      image_group_id: I5355
      title: ''
      volume_number: 61
      total_pages: 622
      base_file: v061.txt
    7f05440054ea497fa74dd10785ec81ef:
      image_group_id: I5356
      title: ''
      volume_number: 62
      total_pages: 618
      base_file: v062.txt
    1acfc771cc1f4ca3ba9063529e317c5c:
      image_group_id: I5357
      title: ''
      volume_number: 63
      total_pages: 598
      base_file: v063.txt
    bd3aeaf5142e4ca297c78ddae1ae5649:
      image_group_id: I5358
      title: ''
      volume_number: 64
      total_pages: 604
      base_file: v064.txt
    b17f60f0b1734106bf9bd2659c46a837:
      image_group_id: I5359
      title: ''
      volume_number: 65
      total_pages: 616
      base_file: v065.txt
    2d476fc2967c426f9ff6c69cc207fec0:
      image_group_id: I5360
      title: ''
      volume_number: 66
      total_pages: 630
      base_file: v066.txt
    edbd3a350b7644ef9366d9d9b5110b31:
      image_group_id: I5361
      title: ''
      volume_number: 67
      total_pages: 642
      base_file: v067.txt
    5a3770227add4c1e9ed4224e899ae7a0:
      image_group_id: I5362
      title: ''
      volume_number: 68
      total_pages: 640
      base_file: v068.txt
    2e632808fcbb487885df603e031db77c:
      image_group_id: I5363
      title: ''
      volume_number: 69
      total_pages: 618
      base_file: v069.txt
    ccdee85e460b4b0a8ded8902c355cd63:
      image_group_id: I5364
      title: ''
      volume_number: 70
      total_pages: 628
      base_file: v070.txt
    bd4e53263f91467c8637692771707a01:
      image_group_id: I5365
      title: ''
      volume_number: 71
      total_pages: 614
      base_file: v071.txt
    4ca5644dc1a54d6c87fb74f10a5e5bdb:
      image_group_id: I5366
      title: ''
      volume_number: 72
      total_pages: 676
      base_file: v072.txt
    b215bea50cae484b85f91083b1d5c634:
      image_group_id: I5367
      title: ''
      volume_number: 73
      total_pages: 622
      base_file: v073.txt
    b222cca0393b4074903ba77a6eaef057:
      image_group_id: I5368
      title: ''
      volume_number: 74
      total_pages: 604
      base_file: v074.txt
    4d006c0d16384161ab6ed28f11fc9992:
      image_group_id: I5369
      title: ''
      volume_number: 75
      total_pages: 600
      base_file: v075.txt
    cb8f2fd83ae0407da3ebce0e86dd77a7:
      image_group_id: I5370
      title: ''
      volume_number: 76
      total_pages: 568
      base_file: v076.txt
    58e1d4fd0c664c66851e77c0058781fd:
      image_group_id: I5371
      title: ''
      volume_number: 77
      total_pages: 310
      base_file: v077.txt
    2769e2ea20304eafb14bddf0afa25647:
      image_group_id: I5372
      title: ''
      volume_number: 78
      total_pages: 738
      base_file: v078.txt
    96bd06f1c7454cf8816fcc2bd848f2ac:
      image_group_id: I5373
      title: ''
      volume_number: 79
      total_pages: 626
      base_file: v079.txt
    cb85aaaae79c4d62894784f01a2cfcb8:
      image_group_id: I5374
      title: ''
      volume_number: 80
      total_pages: 588
      base_file: v080.txt
    70b1059a6d9c4150aaae3a3e1918edca:
      image_group_id: I5375
      title: ''
      volume_number: 81
      total_pages: 690
      base_file: v081.txt
    5ffed418ce1f408782ba30fcde326792:
      image_group_id: I5376
      title: ''
      volume_number: 82
      total_pages: 576
      base_file: v082.txt
    4faac34b318e4cba8ea5dfde1dd3d04b:
      image_group_id: I5377
      title: ''
      volume_number: 83
      total_pages: 712
      base_file: v083.txt
    a0668bc1dd6c499a8734b3651606a192:
      image_group_id: I5378
      title: ''
      volume_number: 84
      total_pages: 610
      base_file: v084.txt
    bbd46282bea84b449036107e696390dc:
      image_group_id: I5379
      title: ''
      volume_number: 85
      total_pages: 552
      base_file: v085.txt
    9b427586591e4572bc48363f65d6a45f:
      image_group_id: I5380
      title: ''
      volume_number: 86
      total_pages: 548
      base_file: v086.txt
    694690dbbdb9466e96b1816fb327cd77:
      image_group_id: I5381
      title: ''
      volume_number: 87
      total_pages: 650
      base_file: v087.txt
    679edf311b534053b27eef6e405a5801:
      image_group_id: I5382
      title: ''
      volume_number: 88
      total_pages: 620
      base_file: v088.txt
    2ce176f936214b7b906fea88157a1022:
      image_group_id: I5383
      title: ''
      volume_number: 89
      total_pages: 708
      base_file: v089.txt
    0d3e57465af9489482ad901113cee113:
      image_group_id: I5384
      title: ''
      volume_number: 90
      total_pages: 588
      base_file: v090.txt
    ad67ade22af146e6b7243ca119f9e066:
      image_group_id: I5385
      title: ''
      volume_number: 91
      total_pages: 576
      base_file: v091.txt
    0a1ecb01e5af4cd8a8556c91a915e8f5:
      image_group_id: I5386
      title: ''
      volume_number: 92
      total_pages: 576
      base_file: v092.txt
    b63b258f7d4d47e381613e00a9bf80b9:
      image_group_id: I5387
      title: ''
      volume_number: 93
      total_pages: 636
      base_file: v093.txt
    7682187dd57e4090be6e8bd0914fe6ec:
      image_group_id: I5388
      title: ''
      volume_number: 94
      total_pages: 624
      base_file: v094.txt
    a44c57429253411682de2ac5a74aa5ae:
      image_group_id: I5389
      title: ''
      volume_number: 95
      total_pages: 558
      base_file: v095.txt
    ca4cf56eba5f45b9be7172eaa491b9b5:
      image_group_id: I5390
      title: ''
      volume_number: 96
      total_pages: 592
      base_file: v096.txt
    12723a1464c946f49366ee25d93253cd:
      image_group_id: I5391
      title: ''
      volume_number: 97
      total_pages: 530
      base_file: v097.txt
    05844da183354bb88877130ea476cfec:
      image_group_id: I5392
      title: ''
      volume_number: 98
      total_pages: 720
      base_file: v098.txt
    afca95538bb44f8c915e5933bd018874:
      image_group_id: I5393
      title: ''
      volume_number: 99
      total_pages: 626
      base_file: v099.txt
    6b586d8878374dab80a04efe46dbc83a:
      image_group_id: I5394
      title: ''
      volume_number: 100
      total_pages: 580
      base_file: v100.txt
    6eac0b74ee354e8dbb5328ae7f475b8e:
      image_group_id: I5395
      title: ''
      volume_number: 101
      total_pages: 570
      base_file: v101.txt
    33281d9bd2bd4c9687746412a54a8b8e:
      image_group_id: I5396
      title: ''
      volume_number: 102
      total_pages: 560
      base_file: v102.txt
    ded9301f98e142c89905e72b9f31a3bb:
      image_group_id: I5397
      title: ''
      volume_number: 103
      total_pages: 714
      base_file: v103.txt
    23cc201d7c5b467a89991f78a2a57abe:
      image_group_id: I5398
      title: ''
      volume_number: 104
      total_pages: 236
      base_file: v104.txt
    9dbceb8885104f85af279857544eda6a:
      image_group_id: I5399
      title: ''
      volume_number: 105
      total_pages: 152
      base_file: v105.txt
